INSERT INTO EMPLOYEE(ID, NAME, ADDRESS)
	VALUES(1, "Tony", "VA");
INSERT INTO EMPLOYEE(ID, NAME, ADDRESS)
	VALUES(2, "Yang", "DC");
INSERT INTO EMPLOYEE(ID, NAME, ADDRESS)
	VALUES(3, "Lily", "FL");	
	